name: Docs & Code Coverage

on: push

jobs:
  docs:
    name: Codecov, Julia 1.5 (Linux, x64)
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: 1.5
          arch: x64
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v1
        with:
          file: ./lcov.info