name: Publish Docker

on:
  push:
    branches:
      - develop
    tags:
      - v*

jobs:
  BuildAndPublish:
    name: Build & Publish
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Get release version
      run: bash .github/scripts/publish-docker.bash
    - name: Enable experimental features
      run: |
        sudo bash -c 'echo "{\"cgroup-parent\": \"/actions_job\", \"experimental\":true}" > /etc/docker/daemon.json'
        sudo systemctl restart docker.service
    - name: Publish to Registry (with a tagged image)
      if: ${{ env.PUBLISH_RELEASE_VERSION == 'true' }}
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: paveloom-j/Exceptions
        username: paveloom
        password: ${{ secrets.GHCR_PAT }}
        registry: ghcr.io
        tags: "latest,stable,${{ env.RELEASE_VERSION }}"
        buildoptions: "--force-rm --squash"
    - name: Publish to Registry (without a tagged image)
      if: ${{ env.PUBLISH_RELEASE_VERSION == 'false' }}
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: paveloom-j/Exceptions
        username: paveloom
        password: ${{ secrets.GHCR_PAT }}
        registry: ghcr.io
        tags: "latest"
        buildoptions: "--force-rm --squash"
